// table of capabilities and their names.
// sorted, 0-40, by number
CN(CAP_CHOWN, "chown", "chown" )
CN(CAP_DAC_OVERRIDE, "dac_override", "ovrd" )
CN(CAP_DAC_READ_SEARCH, "dac_read_search" , "dacrs" )
CN(CAP_FOWNER, "fowner", "fown" )
CN(CAP_FSETID, "fsetid", "fsid" )
CN(CAP_KILL, "kill", "kill" )
CN(CAP_SETGID, "setgid", "sgid" )
CN(CAP_SETUID, "setuid", "suid" )
CN(CAP_SETPCAP, "setpcap", "spcap" )
CN(CAP_LINUX_IMMUTABLE, "linux_immutable", "immutable" )
CN(CAP_NET_BIND_SERVICE, "net_bind_service", "bind" )
CN(CAP_NET_BROADCAST, "net_broadcast", "brdcast" )
CN(CAP_NET_ADMIN, "net_admin", "netadmin" )
CN(CAP_NET_RAW, "net_raw", "netraw" )
CN(CAP_IPC_LOCK, "ipc_lock", "ilock" )
CN(CAP_IPC_OWNER, "ipc_owner", "iown" )
CN(CAP_SYS_MODULE, "sys_module", "module" )
CN(CAP_SYS_RAWIO, "sys_rawio", "rawio" )
CN(CAP_SYS_CHROOT, "sys_chroot", "chroot" )
CN(CAP_SYS_PTRACE, "sys_ptrace", "ptrace" )
CN(CAP_SYS_PACCT, "sys_pacct", "pacct" )
CN(CAP_SYS_ADMIN, "sys_admin", "admin" )
CN(CAP_SYS_BOOT, "sys_boot", "boot" )
CN(CAP_SYS_NICE, "sys_nice", "nice" )
CN(CAP_SYS_RESOURCE, "sys_resource", "resource" )
CN(CAP_SYS_TIME, "sys_time", "time" )
CN(CAP_SYS_TTY_CONFIG, "sys_tty_config", "ttyconf" )
CN(CAP_MKNOD, "mknod", "mknod" )
CN(CAP_LEASE, "lease", "lease" )
CN(CAP_AUDIT_WRITE, "audit_write", "auditw" )
CN(CAP_AUDIT_CONTROL, "audit_control", "auditc" )
CN(CAP_SETFCAP, "setfcap", "fcap" )
CN(CAP_MAC_OVERRIDE, "mac_override", "macovrd" )
CN(CAP_MAC_ADMIN, "mac_admin", "macadmin" )
CN(CAP_SYSLOG, "syslog", "log" )
CN(CAP_WAKE_ALARM, "wake_alarm", "wake" )
CN(CAP_BLOCK_SUSPEND, "block_suspend", "blksusp" )
CN(CAP_AUDIT_READ, "audit_read", "auditr" )
CN(CAP_PERFMON, "perfmon", "pmon" )
CN(CAP_BPF, "bpf", "bpf" )
CN(CAP_CHECKPOINT_RESTORE, "checkpoint_restore", "chkpoint" )


 //C(CAP_EPOLLWAKEUP, "epollwakeup" ) // same as BLOCK_SUSPEND
