// table of capabilities and their names.
// sorted, 0-40, by number
CN(CHOWN, "chown", "chown" )
CN(DAC_OVERRIDE, "dac_override", "ovrd" )
CN(DAC_READ_SEARCH, "dac_read_search" , "dacrs" )
CN(FOWNER, "fowner", "fown" )
CN(FSETID, "fsetid", "fsid" )
CN(KILL, "kill", "kill" )
CN(SETGID, "setgid", "sgid" )
CN(SETUID, "setuid", "suid" )
CN(SETPCAP, "setpcap", "spcap" )
CN(LINUX_IMMUTABLE, "linux_immutable", "immutable" )
CN(NET_BIND_SERVICE, "net_bind_service", "bind" )
CN(NET_BROADCAST, "net_broadcast", "brdcast" )
CN(NET_ADMIN, "net_admin", "netadmin" )
CN(NET_RAW, "net_raw", "netraw" )
CN(IPC_LOCK, "ipc_lock", "ilock" )
CN(IPC_OWNER, "ipc_owner", "iown" )
CN(SYS_MODULE, "sys_module", "module" )
CN(SYS_RAWIO, "sys_rawio", "rawio" )
CN(SYS_CHROOT, "sys_chroot", "chroot" )
CN(SYS_PTRACE, "sys_ptrace", "ptrace" )
CN(SYS_PACCT, "sys_pacct", "pacct" )
CN(SYS_ADMIN, "sys_admin", "admin" )
CN(SYS_BOOT, "sys_boot", "boot" )
CN(SYS_NICE, "sys_nice", "nice" )
CN(SYS_RESOURCE, "sys_resource", "resource" )
CN(SYS_TIME, "sys_time", "time" )
CN(SYS_TTY_CONFIG, "sys_tty_config", "ttyconf" )
CN(MKNOD, "mknod", "mknod" )
CN(LEASE, "lease", "lease" )
CN(AUDIT_WRITE, "audit_write", "auditw" )
CN(AUDIT_CONTROL, "audit_control", "auditc" )
CN(SETFCAP, "setfcap", "fcap" )
CN(MAC_OVERRIDE, "mac_override", "macovrd" )
CN(MAC_ADMIN, "mac_admin", "macadmin" )
CN(SYSLOG, "syslog", "log" )
CN(WAKE_ALARM, "wake_alarm", "wake" )
CN(BLOCK_SUSPEND, "block_suspend", "blksusp" )
CN(AUDIT_READ, "audit_read", "auditr" )
CN(PERFMON, "perfmon", "pmon" )
CN(BPF, "bpf", "bpf" )
CN(CHECKPOINT_RESTORE, "checkpoint_restore", "chkpoint" )


 //C(CAP_EPOLLWAKEUP, "epollwakeup" ) // same as BLOCK_SUSPEND
